const content=document.querySelector('#content'),title=document.querySelector('#page-title'),subtitle=document.querySelector('#page-subtitle');
const esc=v=>String(v??'Not available').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const statusLabel=s=>String(s||'UNKNOWN').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const tone=s=>['LONG_RUNNING','STUCK_NOT_PROGRESSING','FAILED'].includes(s)?'red':['RUNNING_NORMAL'].includes(s)?'green':'amber';
let current=location.pathname.toLowerCase()==='/logs'?'logs':'etl',lastModels=[],nextCycleRemaining=null;
function metric(label,value,note,color='var(--cyan)',category=''){category=category||({'Successful model runs':'successful','Long running till now':'long_running','Stuck till now':'stuck','Total model runs':'total'})[label]||'';return `<article class="metric${category?' clickable-metric':''}" style="--tone:${color}"${category?` data-history-category="${category}" role="button" tabindex="0" aria-label="View ${esc(label)} history"`:''}><div class="metric-label">${label}</div><div class="metric-value">${esc(value)}</div><div class="metric-note">${note}</div></article>`}
async function request(path){const r=await fetch(path);if(!r.ok){const e=await r.json().catch(()=>({}));throw new Error(e.detail||`Request failed (${r.status})`)}return r.json()}
async function load(refresh=false){const initial=content.dataset.view!==current;if(current==='configure'){renderConfigure();content.dataset.view=current;return}if(initial)content.innerHTML='<div class="loading"><span></span><p>Synchronizing telemetry...</p></div>';content.classList.add('updating');try{if(current==='etl')renderEtlProgress(await request('/api/etl'));else if(current==='models'){const [models,stats]=await Promise.all([request(`/api/models${refresh?'?refresh=true':''}`),request('/api/models/stats').catch(()=>null)]);renderModels(models,stats)}else renderLogs(await request('/api/logs'));content.dataset.view=current}catch(e){if(initial)content.innerHTML=`<div class="alert"><strong>Telemetry unavailable</strong><p>${esc(e.message)}</p></div>`}finally{content.classList.remove('updating')}}
function renderLogs(data){const scheduler=(data.scheduler||[]).join(''),monitoring=(data.model_monitoring||[]).join('');content.innerHTML=`<div class="logs-grid"><section class="panel log-panel"><div class="panel-heading"><h2>Process scheduler</h2><span class="panel-tag">LIVE · LAST 500 LINES</span></div><pre>${esc(scheduler||'No scheduler logs available.')}</pre></section><section class="panel log-panel"><div class="panel-heading"><h2>Model monitoring</h2><span class="panel-tag">LIVE · LAST 500 LINES</span></div><pre>${esc(monitoring||'No model-monitoring logs available.')}</pre></section></div>`;document.querySelectorAll('.log-panel pre').forEach(el=>el.scrollTop=el.scrollHeight)}
function slugify(value){return String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,63)}
function renderConfigure(){
  content.innerHTML=`<section class="panel configure-panel"><div class="panel-heading"><div><p class="eyebrow">CLIENT ONBOARDING</p><h2>Create Monitoring Package</h2></div><span class="panel-tag">SPM TEMPLATE</span></div><p class="configure-intro">Generate a client-ready Obero Monitoring package from the approved process template. Client IDs, names, and staging tables are updated consistently throughout the workflow.</p><form id="package-form" class="configure-form"><label>Client ID<input name="client_id" type="number" min="1" required placeholder="5"><small id="client-id-help">Checking existing client IDs…</small></label><label>Client name<input name="client_name" maxlength="100" required placeholder="newclient"><small>Exact CLIENTNAME written by the process.</small></label><label>Staging table prefix<input name="staging_prefix" pattern="[a-z][a-z0-9_]{1,62}" required placeholder="newclient"><small>Creates delta.&lt;prefix&gt;_cea_* references.</small></label><label>Process ID<input class="disabled-input" type="number" value="143" disabled><input name="process_id" type="hidden" value="143"><small>Fixed by the approved template.</small></label><label class="wide">Package / process name<input name="package_name" maxlength="100" value="Monitoring" required></label><div class="wide configure-actions"><button class="generate-button" type="submit" disabled>Generate .spm package</button><span id="package-status" aria-live="polite"></span></div></form><div class="template-note"><strong>Template safeguards</strong><span>Updates all client filters, source constants, target filters, and staging table names. The original template remains unchanged.</span></div></section>`;
  const form=document.querySelector('#package-form'),name=form.elements.client_name,prefix=form.elements.staging_prefix,clientId=form.elements.client_id,button=form.querySelector('.generate-button'),seededIds=window.__CONFIGURED_CLIENT_IDS__;let prefixEdited=false,existingIds=new Set(Array.isArray(seededIds)?seededIds.map(Number):[]),idsLoaded=Array.isArray(seededIds);prefix.oninput=()=>prefixEdited=true;name.oninput=()=>{if(!prefixEdited)prefix.value=slugify(name.value)};const validateClientId=()=>{const value=Number(clientId.value),duplicate=clientId.value!==''&&existingIds.has(value),help=document.querySelector('#client-id-help');clientId.setCustomValidity(duplicate?`Client ID ${value} already exists`:'');clientId.classList.toggle('input-invalid',duplicate);button.disabled=!idsLoaded||duplicate;help.className=duplicate?'error-text':'';help.textContent=duplicate?`Client ID ${value} already exists.`:idsLoaded?`Existing client IDs: ${[...existingIds].join(', ')||'none'}`:'Checking existing client IDs…'};clientId.oninput=validateClientId;if(idsLoaded){validateClientId()}else{request('/api/configure/clients').then(data=>{existingIds=new Set((data.client_ids||[]).map(Number));idsLoaded=true;validateClientId()}).catch(error=>{button.disabled=true;const help=document.querySelector('#client-id-help');help.className='error-text';help.textContent=`Could not check client IDs: ${error.message}`})}form.onsubmit=generatePackage;
}
async function generatePackage(event){event.preventDefault();const form=event.currentTarget,status=document.querySelector('#package-status'),button=form.querySelector('button');button.disabled=true;status.className='';status.textContent='Generating package…';const body=Object.fromEntries(new FormData(form));body.client_id=Number(body.client_id);body.process_id=Number(body.process_id);try{const response=await fetch('/api/configure/package',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.detail||`Generation failed (${response.status})`)}const blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',match=disposition.match(/filename="?([^";]+)"?/),filename=match?match[1]:`${body.staging_prefix}-monitoring.spm`,url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);status.className='success-text';status.textContent=`Downloaded ${filename}`}catch(error){status.className='error-text';status.textContent=error.message}finally{button.disabled=Boolean(form.elements.client_id.validationMessage)}}
function renderEtl(data){const s=data.summary,sch=data.scheduler,total=s.successful+s.failed,deg=total?s.successful/total*360:0;content.innerHTML=`<div class="metrics">${metric('Successful runs',s.successful,'Completed without incident','var(--green)')}${metric('Failed runs',s.failed,'Requires operator attention','var(--red)')}${metric('Success rate',`${s.success_rate}%`,'Across observed executions','var(--cyan)')}${metric('Cycles monitored',s.cycles,'Scheduler observation window','var(--violet)')}</div><div class="section-grid"><section class="panel"><div class="panel-heading"><h2>Execution outcomes</h2><span class="panel-tag">LAST ${s.cycles} CYCLES</span></div><div class="donut-wrap"><div class="donut" style="background:conic-gradient(var(--green) 0 ${deg}deg,var(--red) ${deg}deg 360deg)"><div class="donut-center"><strong>${s.success_rate}%</strong><small>SUCCESS RATE</small></div></div><div class="legend"><p><span><i style="background:var(--green)"></i>Successful</span><b>${s.successful}</b></p><p><span><i style="background:var(--red)"></i>Failed</span><b>${s.failed}</b></p><p><span><i style="background:#344155"></i>Total runs</span><b>${total}</b></p></div></div></section><section class="panel"><div class="panel-heading"><h2>Scheduler health</h2><span class="pill ${sch.running?'green':'red'}">${sch.running?'OPERATIONAL':'OFFLINE'}</span></div><div class="status-card"><div class="status-icon">◉</div><div><strong>${sch.enabled?'Automation service':'Automation disabled'}</strong><small>${esc(sch.message)}</small></div></div><div class="status-card"><div class="status-icon">⌁</div><div><strong>Last cycle</strong><small>${esc(s.last_completed_at||'Awaiting first cycle')}</small></div></div><p class="data-source">Process ID: ${esc(sch.pid||'—')}</p></section></div>`}
function renderEtlProgress(data){
  renderEtl(data);
  const p=data.current_progress||{},percent=Math.max(0,Math.min(100,Number(p.percent)||0));
  const cycle=p.cycle?`Cycle ${p.cycle}`:'Next cycle';
  const detail=p.total?`${p.completed} of ${p.total} clients completed`:'Waiting for scheduler activity';
  nextCycleRemaining=p.remaining_seconds==null?null:Number(p.remaining_seconds);
  content.insertAdjacentHTML('afterbegin',`<section class="progress-panel"><div class="progress-head"><div><h2>Current ETL progress · ${esc(cycle)}</h2><p>${esc(detail)} · ${esc(statusLabel(p.state||'waiting'))}${p.started_at?` · Started ${esc(p.started_at)}`:''}</p></div><div class="progress-actions"><div class="cycle-countdown"><small>NEXT CYCLE IN</small><strong id="cycle-countdown">${formatCountdown(nextCycleRemaining)}</strong></div><button id="history-button" class="history-button"><span class="history-pulse">⌁</span> View ETL runs</button><div class="progress-percent">${percent}%</div></div></div><div class="progress-track" role="progressbar" aria-valuenow="${percent}" aria-valuemin="0" aria-valuemax="100"><div class="progress-fill" style="width:${percent}%"></div></div></section>`);
  document.querySelector('#history-button').onclick=openHistory;
}
function localDate(){const d=new Date(),offset=d.getTimezoneOffset()*60000;return new Date(d-offset).toISOString().slice(0,10)}
function openHistory(){
  document.querySelector('#drawer-content').innerHTML=`<span class="pill green">ETL ARCHIVE</span><h2>Run history</h2><p class="recommend">Select a date to inspect completed cycles and their processing time.</p><label class="date-label" for="history-date">Run date</label><input id="history-date" class="date-picker" type="date" value="${localDate()}"><div id="history-results" class="history-results"><div class="loading mini"><span></span><p>Loading runs...</p></div></div>`;
  document.querySelector('#drawer').classList.add('open');document.querySelector('#drawer-backdrop').classList.add('open');
  const picker=document.querySelector('#history-date');picker.onchange=()=>loadHistory(picker.value);loadHistory(picker.value);
}
async function loadHistory(runDate){
  const target=document.querySelector('#history-results');target.innerHTML='<div class="loading mini"><span></span><p>Loading runs...</p></div>';
  try{const data=await request(`/api/etl/history?run_date=${encodeURIComponent(runDate)}`),runs=data.runs||[];target.innerHTML=runs.length?`<div class="history-summary"><strong>${runs.length}</strong><span>completed cycle${runs.length===1?'':'s'}</span></div>${runs.map(run=>`<article class="history-run"><div class="history-cycle"><span class="pill ${run.failed?'red':'green'}">${run.failed?'ISSUES':'SUCCESS'}</span><strong>Cycle ${esc(run.cycle)}</strong><small>${esc(run.completed_at)}</small></div><div class="history-duration"><strong>${formatDuration(run.duration_seconds)}</strong><small>${run.successful}/${run.total} successful</small></div></article>`).join('')}`:'<div class="empty">No completed ETL runs found for this date.</div>'}catch(e){target.innerHTML=`<div class="alert">${esc(e.message)}</div>`}
}
function formatDuration(seconds){const value=Number(seconds)||0;if(value<60)return `${value.toFixed(1)} sec`;const mins=Math.floor(value/60),secs=Math.round(value%60);return `${mins}m ${secs}s`}
function formatCountdown(seconds){if(seconds==null)return '--:--';const value=Math.max(0,Math.floor(seconds)),hours=Math.floor(value/3600),mins=Math.floor((value%3600)/60),secs=value%60;return hours?`${String(hours).padStart(2,'0')}:${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`:`${String(mins).padStart(2,'0')}:${String(secs).padStart(2,'0')}`}
function renderModels(data,history){const r=data.result||{},runs=Array.isArray(r.client_results)?r.client_results:[];lastModels=runs;const count=s=>runs.filter(x=>x.status===s).length,fallback={total:runs.length,successful:count('RUNNING_NORMAL'),long_running:count('LONG_RUNNING'),stuck:count('STUCK_NOT_PROGRESSING')},stats=history||fallback;if(['DATA_REFRESH_IN_PROGRESS','DATA_REFRESH_FAILED','TELEMETRY_INITIALIZING'].includes(r.overall_status)){content.innerHTML=`<div class="alert"><strong>${statusLabel(r.overall_status)}</strong><p>${esc(r.error_message||r.summary||'Monitoring calculations are temporarily paused.')}</p></div>`;return}content.innerHTML=`<div class="metrics">${metric('Successful model runs',stats.successful,'Completed without long-running or stuck status','var(--green)')}${metric('Long running till now',stats.long_running,'Historical runs flagged long-running','var(--red)')}${metric('Stuck till now',stats.stuck,'Historical runs flagged as stuck','var(--amber)')}${metric('Total model runs',stats.total,'All model runs recorded','var(--cyan)')}</div><section class="panel run-list"><div class="panel-heading"><h2>Live model executions</h2><span class="panel-tag">${data.refreshing?'UPDATING':data.cached?'CACHED':'FRESH'} · ${esc(data.metrics?.data_source?.toUpperCase())}</span></div>${runs.length?runs.map((x,i)=>`<article class="run-row" data-index="${i}"><div><strong>${esc(x.clientname||'Unknown client')}</strong><small>Client ${esc(x.clientid)}</small></div><div><strong>${esc(x.model_caption||x.model_key||'—')}</strong><small>Model</small></div><div><strong>${esc(x.current_step||x.long_running_step||'Waiting')}</strong><small>Current step</small></div><div><span class="pill ${tone(x.status)}">${esc(statusLabel(x.status))}</span></div><div>›</div></article>`).join(''):'<div class="empty">No active model executions detected.</div>'}<p class="data-source">Loaded in ${esc(data.metrics?.total_seconds)}s · ${Object.entries(data.row_counts||{}).map(([k,v])=>`${esc(k)}: ${v}`).join(' · ')}</p></section>`;document.querySelectorAll('.run-row').forEach(el=>el.onclick=()=>openDrawer(lastModels[Number(el.dataset.index)]))}
function openDrawer(x){const evidence=Array.isArray(x.evidence)?x.evidence:[],drawer=document.querySelector('#drawer');drawer.classList.remove('fullscreen');document.querySelector('#drawer-content').innerHTML=`<span class="pill ${tone(x.status)}">${esc(statusLabel(x.status))}</span><h2>${esc(x.clientname||'Model run')}</h2><p class="recommend">${esc(x.recommendation||'Continue monitoring.')}</p><div class="detail-grid">${[['Client ID',x.clientid],['Model',x.model_caption||x.model_key],['Trigger time',x.trigger_time],['Current step',x.current_step||x.long_running_step],['Minutes over average',x.minutes_over_average==null?'0.0 min':`${x.minutes_over_average} min`],['Model key',x.model_key]].map(([a,b])=>`<div class="detail"><label>${a}</label><div>${esc(b)}</div></div>`).join('')}</div><h3>Evidence trail</h3>${evidence.length?evidence.map(e=>`<div class="evidence">${esc(e)}</div>`).join(''):'<div class="empty">No evidence returned.</div>'}<button id="model-history-button" class="history-button model-history-button"><span class="history-pulse">⌁</span> Model Run history</button>`;document.querySelector('#model-history-button').onclick=()=>openModelHistory(x);drawer.classList.add('open');document.querySelector('#drawer-backdrop').classList.add('open')}
function closeDrawer(){const drawer=document.querySelector('#drawer');drawer.classList.remove('open','fullscreen');document.querySelector('#drawer-backdrop').classList.remove('open')}
function historyRun(run){const steps=Array.isArray(run.steps)?run.steps:[],minutesOver=Number(run.minutes_over_average)||0,notified=minutesOver>20?1:0,flaggedIndex=steps.findIndex(s=>Number(s.notified_by_agent)===1&&Number(s.minutes_over_average)>20);return `<details class="model-history-run"><summary><span><strong>${esc(run.trigger_time||run.first_seen_at)}</strong><small>${esc(run.model_caption||run.model_key||'Model run')} · Click to view details</small></span><span class="pill ${tone(run.status)}">${esc(statusLabel(run.status))}</span><span class="notification-value">Notified by agent: <b>${notified}</b></span></summary><div class="history-run-meta"><span>Current duration: <b>${formatDuration(run.run_duration_seconds)}</b></span><span>Historical average: <b>${formatDuration(run.average_duration_seconds)}</b></span><span>Minutes over average: <b>${minutesOver.toFixed(1)} min</b></span><span>Notification rule: <b>${minutesOver.toFixed(1)} &gt; 20 min = ${notified}</b></span><span>Alert-causing step: <b>${esc(flaggedIndex>=0?steps[flaggedIndex].description:'None')}</b></span></div><div class="step-table-wrap"><table class="step-table"><thead><tr><th>Step</th><th>Details</th><th>Start time</th><th>Duration</th><th>Average time</th><th>Minutes over average</th><th>Compared runs</th><th>Notified by agent</th></tr></thead><tbody>${steps.length?steps.map((s,i)=>{const stepOver=Number(s.minutes_over_average??Math.max(0,(Number(s.duration_seconds||0)-Number(s.average_duration_seconds||0))/60)),stepNotified=i===flaggedIndex&&stepOver>20?1:0;return `<tr class="${stepNotified?'agent-flagged-step':''}"><td>${esc(s.step_no||`${i+1}/${steps.length}`)}</td><td>${esc(s.description||'')}</td><td>${esc(s.created_date||'')}</td><td>${formatDuration(s.duration_seconds)}</td><td>${formatDuration(s.average_duration_seconds)}</td><td>${stepOver.toFixed(1)} min</td><td>${esc(s.comparison_sample_count??'—')}</td><td>${stepNotified}</td></tr>`}).join(''):`<tr><td colspan="8">No step telemetry captured.</td></tr>`}</tbody></table></div></details>`}
function modelHistoryScreen(model,runs,backLabel,notifiedOnly){const visible=notifiedOnly?runs.filter(run=>Number(run.notified_by_agent)===1):runs;return `<button id="history-back" class="drawer-back">‹ ${backLabel}</button><div class="model-history-heading"><div><span class="pill green">MODEL ARCHIVE</span><h2>Model Run history</h2><p class="recommend">${esc(model.clientname)} · ${esc(model.model_caption||model.model_key)}</p></div><label class="history-filter-label">Show<select id="model-history-filter" class="history-filter"><option value="all" ${notifiedOnly?'':'selected'}>All runs</option><option value="notified" ${notifiedOnly?'selected':''}>Notified by agent</option></select></label></div><p class="history-count">Showing ${visible.length} of ${runs.length} run${runs.length===1?'':'s'} · Select a run to view all step details</p>${visible.length?visible.map(historyRun).join(''):`<div class="empty">${notifiedOnly?'No runs were notified by the agent.':'No previous model runs found.'}</div>`}`}
async function openModelHistory(model,backToEvidence=true){const target=document.querySelector('#drawer-content'),drawer=document.querySelector('#drawer'),back=()=>backToEvidence?openDrawer(model):closeDrawer(),backLabel=backToEvidence?'Back to evidence':'Back to Application Runs';target.innerHTML='<div class="loading mini"><span></span><p>Loading model run history...</p></div>';drawer.classList.add('open','fullscreen');document.querySelector('#drawer-backdrop').classList.add('open');try{const query=new URLSearchParams({client_id:String(model.clientid||''),model_key:String(model.model_key||''),limit:'1000'});const data=await request(`/api/models/history?${query}`),runs=data.runs||[];const show=notifiedOnly=>{target.innerHTML=modelHistoryScreen(model,runs,backLabel,notifiedOnly);document.querySelector('#history-back').onclick=back;document.querySelector('#model-history-filter').onchange=e=>show(e.target.value==='notified')};show(false)}catch(e){target.innerHTML=`<button id="history-back" class="drawer-back">‹ ${backLabel}</button><div class="alert">${esc(e.message)}</div>`;document.querySelector('#history-back').onclick=back}}
const historyCategoryLabels={successful:'Successful model runs',long_running:'Long running till now',stuck:'Stuck till now',total:'Total model runs'};
async function openCategoryHistory(category){const target=document.querySelector('#drawer-content'),drawer=document.querySelector('#drawer'),label=historyCategoryLabels[category]||'Model runs';target.innerHTML='<div class="loading mini"><span></span><p>Loading model run history...</p></div>';drawer.classList.add('open','fullscreen');document.querySelector('#drawer-backdrop').classList.add('open');try{const query=new URLSearchParams({category,limit:'5000'}),data=await request(`/api/models/history?${query}`),runs=data.runs||[];target.innerHTML=`<button id="history-back" class="drawer-back">‹ Back to Application Runs</button><div class="model-history-heading"><div><span class="pill green">MODEL ARCHIVE</span><h2>${esc(label)}</h2><p class="recommend">Model Run history</p></div></div><p class="history-count">Showing ${runs.length} run${runs.length===1?'':'s'} · Select a run to view all step details</p>${runs.length?runs.map(historyRun).join(''):'<div class="empty">No model runs found in this category.</div>'}`;document.querySelector('#history-back').onclick=closeDrawer}catch(e){target.innerHTML=`<button id="history-back" class="drawer-back">‹ Back to Application Runs</button><div class="alert">${esc(e.message)}</div>`;document.querySelector('#history-back').onclick=closeDrawer}}
function activateHistoryTile(target){const tile=target.closest('[data-history-category]');if(tile)openCategoryHistory(tile.dataset.historyCategory)}
document.addEventListener('click',event=>activateHistoryTile(event.target));
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-history-category]')){event.preventDefault();activateHistoryTile(event.target)}});
const pages={etl:['ETL Operations','Process health, throughput and execution outcomes.'],models:['Application Runs','Active model health, anomalies and agent evidence.'],configure:['Configure','Create a monitoring package for a new client.'],logs:['System Logs','Live scheduler and model-monitoring output.']};
document.querySelectorAll('.nav-item').forEach(btn=>{btn.classList.toggle('active',btn.dataset.view===current);btn.onclick=()=>{document.querySelector('.nav-item.active')?.classList.remove('active');btn.classList.add('active');current=btn.dataset.view;history.replaceState({},'','/');title.textContent=pages[current][0];subtitle.textContent=pages[current][1];document.querySelector('#refresh').hidden=current==='configure';load()}});
title.textContent=pages[current][0];subtitle.textContent=pages[current][1];document.querySelector('#refresh').hidden=current==='configure';
document.querySelector('#refresh').onclick=()=>load(true);document.querySelector('#drawer-close').onclick=closeDrawer;document.querySelector('#drawer-backdrop').onclick=closeDrawer;document.addEventListener('keydown',e=>e.key==='Escape'&&closeDrawer());load();
setInterval(()=>{if(current==='etl'&&!document.hidden)load(false)},10000);
setInterval(()=>{if(current==='logs'&&!document.hidden)load(false)},5000);
setInterval(()=>{if(current!=='etl'||nextCycleRemaining==null)return;nextCycleRemaining=Math.max(0,nextCycleRemaining-1);const display=document.querySelector('#cycle-countdown');if(display)display.textContent=formatCountdown(nextCycleRemaining)},1000);
